name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper/
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Decode keystore (if releasing)
      if: secrets.KEYSTORE_BASE64
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/keystore.jks

    - name: Grant execute permission on gradlew
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Build Release APK
      if: secrets.KEYSTORE_BASE64
      run: |
        cat <<EOF >> app/gradle.properties
        android.injected.signing.store.file=app/keystore.jks
        android.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }}
        android.injected.signing.key.alias=${{ secrets.KEY_ALIAS }}
        android.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}
        EOF
        ./gradlew assembleRelease

    - name: Upload APKs
      uses: actions/upload-artifact@v3
      with:
        name: app-apks
        path: |
          app/build/outputs/apk/debug/app-debug.apk
          app/build/outputs/apk/release/app-release.apk